### ISSUE TITLE
[FEAT] main / 바텀네비게이션 바 구현

### ISSUE THREAD

**Issue by etama123** [Keyneez/Keyneez-AOS-Release#7]
## ISSUE
- main / 바텀네비게이션 바 구현

## To-Do
- [ ] ~~홈, 탐색, 마이페이지, 설정 순으로 만들기~~ 확정나면 제작할게요
- [ ] BottomNavigation vs Bottom Appbar 고민해보기

**Comment by b1urrrr** [comment]
@DongjooSEO 이슈 컨벤션 한번만 확인 부탁드립니다~

**Comment by b1urrrr** [comment]
베타 서비스 이슈 새로 팔 예정
